-- Shopify full catalog sync support tables
-- Run this once in Supabase > SQL Editor.
-- Existing warehouse tables (products, stock_history, etc.) are not modified.

create table if not exists public.shopify_sync_rules (
  colorme_product_id bigint primary key,
  shopify_mode text not null default 'auto'
    check (shopify_mode in ('auto', 'force_draft', 'force_active', 'force_archive')),
  is_reserved boolean not null default false,
  allow_variant_delete boolean not null default false,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.shopify_sync_rules
  add column if not exists allow_variant_delete boolean not null default false;

create table if not exists public.shopify_sync_mappings (
  colorme_product_id bigint primary key,
  shopify_product_id text not null unique,
  source_hash text,
  image_hash text,
  last_status text,
  last_synced_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shopify_sync_errors (
  id bigint generated by default as identity primary key,
  error_key text not null unique,
  error_type text not null,
  colorme_product_id bigint,
  sku text,
  message text not null,
  details jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  first_occurred_at timestamptz not null default now(),
  last_occurred_at timestamptz not null default now(),
  resolved_at timestamptz,
  last_run_id uuid
);

create table if not exists public.shopify_sync_runs (
  id uuid primary key,
  mode text not null default 'incremental',
  status text not null default 'running'
    check (status in ('running', 'success', 'partial', 'failed', 'dry_run')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  fetched_products integer not null default 0,
  processed_products integer not null default 0,
  created_products integer not null default 0,
  updated_products integer not null default 0,
  skipped_products integer not null default 0,
  error_count integer not null default 0,
  summary jsonb not null default '{}'::jsonb
);

create index if not exists shopify_sync_errors_active_idx
  on public.shopify_sync_errors (active, last_occurred_at desc);

create index if not exists shopify_sync_errors_product_idx
  on public.shopify_sync_errors (colorme_product_id);

create index if not exists shopify_sync_runs_started_idx
  on public.shopify_sync_runs (started_at desc);

create or replace function public.set_shopify_sync_rule_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists shopify_sync_rules_set_updated_at
  on public.shopify_sync_rules;

create trigger shopify_sync_rules_set_updated_at
before update on public.shopify_sync_rules
for each row execute function public.set_shopify_sync_rule_updated_at();

alter table public.shopify_sync_rules enable row level security;
alter table public.shopify_sync_mappings enable row level security;
alter table public.shopify_sync_errors enable row level security;
alter table public.shopify_sync_runs enable row level security;

-- No anon/authenticated policies are intentionally added.
-- The Vercel server routes and Sakura cron use the service role key.
